### ISSUE TITLE
enumerators' `opam` should list `"ocamlbuild" {build}` in its dependencies

### ISSUE THREAD

**Issue by gasche** [cryptosense/enumerators#3]
opam-builder report: http://opam.ocamlpro.com/builder/html/enumerators/enumerators.0.1.1/31c939e2c086863dec92f1ee0bcd4902

**Comment by bbc2** [comment]
Thank you!  The next version will fix this.

**Comment by emillon** [comment]
N.B. if only the `opam` file changes, no need to release a version, a PR on `opam-repository` will be enough.

**Comment by bbc2** [comment]
Right!

**Comment by gasche** [comment]
I did the `opam-repository` PR (see above). Indeed, there is no need to have a release, I just wanted to get this into your upstream `opam` -- I believe that `0.1.0` had the correct metadata, but that `0.1.1` was released later without looking at the `opam-repository` changes for improvements.

Thanks for your reactivity!
